#!/bin/bash





info(){


zenity --info \
       --title "KYGnus Info" \
       --width 900 \
       --height 100 \
       --text """																KYGnus
									
Hobbit Archive


I wrote this software for fun and variety and decided to publish it. Linux is fast, Linux is strong, and Linux is one of the symbols of freedom. According to Richard Stallman, Linux is a big hack and it clearly shows the logic and thinking of the people behind this issue. In order to attract more people and introduce them to the idea of the logic and complexity of Linux, I decided to create a graphic information archive program. I will write and show that it is very easy and simple to make a simple product in Linux. For those who use an operating system other than the Unix family, I recommend paying attention to the size of the file!!!	
"""




}


status(){
	
	
	# I put the database settings inside the file and I don't need to enter the user and password every time I log in to the system
	# mysql -u root -p
	database_check=`mysql --execute="show databases;"`
	 zenity --list \
		 --column "databases" \
		 --width 900 \
		 --height 500 \
		#$database_check

}

insert_data(){

	zenity --forms \
	       --text "Welcome to signup wizard" \
	       --height 500 \
	       --width 900 \
	       --add-entry "Enter the first name" \
	       --add-entry "Enter the last name" \
	       --add-entry "Enter Department" \
	       --add-password "Enter UserID"

	musql --execute="use test_data;INSERT INTO userinfo (\`First_Name\`, \`Last_Name\`, \`Department\`, \`UserID\`) "

	zenity --info \
	       --title "MariaDB Message" \
	       --width 500 \
	       --height 100 \
	       --text "Data Inserted successfully."

}




login(){


	userinfo=`zenity --username --password`
	username=`echo $userinfo | cut -d "|" -f1`
	password=`echo $userinfo | cut -d "|" -f2`

	if [ "$username" == "koosha" ] && [ "$password" == "102030" ];then
		insert_data
	else

		zenity --error \
		       --title "Error Message" \
		       --width 800 \
		       --height 100 \
		       --text "Permission denied. UserName or Password is Invalid"
		exit 0
fi


}

public_error(){

		zenity --error \
		       --title "Error Message" \
		       --width 800 \
		       --height 100 \
		       --text "Permission denied. UserName or Password is Invalid"



}


